---
title: "Day 4 - Exploring Data"
author: "Victoria Cutler"
format: html
editor: visual
---

```{r}
#| warning: false
#| echo: false ## if there are outputs, they will show, but the code will not

library(tidyverse)
library(palmerpenguins)
library(GGally) ## install.packages("GGally")
library(skimr)
```

## Exploratory Data Viz

Check out your data a bit (may normally just run these in the console):

```{r}
#| include: false ## nothing will show up from this code chunk now in my rendered doc, neither the outputs or code

## Tell me the column names:
names(penguins)

## What are the dimensions?
dim(penguins)

## Can you show me the first 6 lines?
head(penguins)

## last 6 lines?
tail(penguins)
```

```{r}
##skim(penguins)
```

```{r}
##GGally::ggpairs(penguins)
```

## Jitterplot

Flipper length by species

```{r}
#| fig.cap = "my awesome figure caption"
ggplot(data = penguins, mapping = aes(x = species,y = flipper_length_mm)) +
  geom_jitter(width = 0.2,
              alpha = 0.5,
              height = 0,
              aes(color = species)) + ##saying what geometry we want aka jitter, then adding some modifications like the spread of the points (width) and transparancy (alpha)
  geom_boxplot(fill = NA) +
  theme_light() + ##change background from grey to white
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) +
  labs(x = "Species", 
       y = "Flipper Length (mm)",
       title = "Penguin Species vs Flipper Length (mm)")
```

```{r}
ggplot(data = penguins, mapping = aes(x = bill_length_mm)) +
  geom_histogram(aes(fill = species), color = "magenta") +
  facet_wrap(~species, ncol = 1)
```
